# Generated by Terraform — do not edit manually
# Environment: ${environment}

services:
  backend:
    build:
      context: ../../../backend
    container_name: ${app_name}_${environment}_backend
    environment:
      NODE_ENV: ${environment}
      PORT: ${backend_port}
      MONGODB_URI: ${mongodb_uri}
      JWT_SECRET: ${jwt_secret}
      BLESSEDTEXTS_API_KEY: ${sms_api_key}
      BLESSEDTEXTS_SENDER: ${sms_sender}
      DEFAULT_SENDER_ID: ${sms_sender}
      SMS_COST_PER_UNIT: ${sms_cost_per_unit}
      CLIENT_URL: ${frontend_url}
      LOG_LEVEL: ${log_level}
    ports:
      - "${backend_port}:${backend_port}"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ../../../
      args:
        VITE_API_URL: http://localhost:${backend_port}/api
    container_name: ${app_name}_${environment}_frontend
    depends_on:
      - backend
    ports:
      - "${frontend_port}:80"

volumes:
  uploads_data:
