# Generated by Terraform — do not edit manually
# Environment: ${environment}

NODE_ENV=${environment}
PORT=${backend_port}
MONGODB_URI=${mongodb_uri}
JWT_SECRET=${jwt_secret}
BLESSEDTEXTS_API_KEY=${sms_api_key}
BLESSEDTEXTS_SENDER=${sms_sender}
DEFAULT_SENDER_ID=${sms_sender}
SMS_COST_PER_UNIT=${sms_cost_per_unit}
CLIENT_URL=${frontend_url}
LOG_LEVEL=${log_level}
RATE_LIMIT_MAX_REQUESTS=${rate_limit}
